export const CHANGE_LANG = 'CHANGE_LANG'
export const FETCH_DATA = 'FETCH_DATA'
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'

export const GTE_SAGA_TEST = 'GTE_SAGA_TEST'
export const GTE_SAGA_TEST_SUCCESS = 'GTE_SAGA_TEST_SUCCESS'